config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :appointments
  resources :availabilities
  resources :rooms
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "rooms#index"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :availabilities, dependent: :destroy
  has_many :appointments, dependent: :destroy
  accepts_nested_attributes_for :availabilities, allow_destroy: true

  after_create :create_availabilities

  after_update_commit { broadcast_replace_to 'rooms' }
  after_destroy_commit { broadcast_remove_to 'rooms' }

  def create_availabilities
    7.times { |i| Availability.create(starts_at: '9:00', ends_at: '17:00', week_day: i, room_id: id) }
  end

  def availabilities_from(date, slot_duration = 30, week_duration = 6)
    date = DateTime.parse(date)
    date_range = generate_date_range(date, week_duration)
    results = generate_results(id, date_range, slot_duration)
    clean_results(results)
  end

  private

  ## Generate a date_range based on a start_date and a duration in days
  def generate_date_range(date, week_duration)
    date.beginning_of_day..(date.end_of_day + week_duration.days - 1.day)
  end

  def generate_results(id, date_range, slot_duration)
    results = format_hash(date_range)
    events = fetch_events(id, date_range)
    week = generate_week(date_range)
    transposed_events = transpose_events(events, week)
    transform_events_in_ranges(transposed_events, results, slot_duration, week)
  end

  def fetch_events(id, date_range)
    Availability.where(room_id: id, week_day: date_range.map(&:wday)) +
      Appointment.where('room_id = ? AND starts_at >= ? AND ends_at <= ?', id, date_range.begin, date_range.end)
  end

  def format_hash(date_range)
    date_range.each_with_object({}) { |day, hash| hash[day.strftime('%Y-%m-%d')] = [[], []] }
  end

  def transpose_events(events, week)
    events.map { |event| event.instance_of?(Availability) ? transform_event(event, week[event.week_day]) : event }
  end

  def generate_week(date_range)
    date_range.each_with_object({}) { |day, hash| hash[day.wday] = day.strftime('%Y-%m-%d') }
  end

  ## Move the date of a single event to the same day in the date_range
  def transform_event(event, day)
    event.starts_at = DateTime.parse("#{day} #{event.starts_at.to_s(:time)}")
    event.ends_at = DateTime.parse("#{day} #{event.ends_at.to_s(:time)}")
    event
  end

  def transform_events_in_ranges(events, results, slot_duration, week)
    events.each do |event|
      day = week[event.week_day]
      if event.instance_of?(Availability)
        availabilities_ranges(event, day, slot_duration, results)
      else
        appointments_ranges(event, day, results)
      end
    end
    results
  end

  def appointments_ranges(event, day, results)
    results[day].second << generate_range(event.starts_at, event.ends_at)
    results
  end

  def availabilities_ranges(event, day, slot_duration, results)
    while event.starts_at < event.ends_at
      results[day].first << generate_range(event.starts_at, event.starts_at + 60 * slot_duration)
      event.starts_at += (60 * slot_duration)
    end
    results
  end

  ## Generate a range for using the start_time and end_time of an event (availability or appointment)
  def generate_range(starts_at, ends_at)
    starts_at.strftime('%H:%M')...ends_at.strftime('%H:%M')
    #starts_at...ends_at
  end

  def clean_results(hash)
    hash.each do |key, _|
      hash[key] = hash[key][0].map do |slot|
        overlap = hash[key][1].map { |booked_slot| (booked_slot).overlaps?(slot) }
        overlap.include?(true) ? '-' : slot
      end
    end
  end



  # availabilities.map do |slot|
  #   overlap = appointments.map { |booked_slot| (booked_slot).overlaps?(slot) }
  #   overlap.include?(true) ? '-' : slot
  # end

end














  #number_of_slots = ((ends_at - starts_at) / 60).to_i / slot_duration
  # durations = Array.new(number_of_slots) { |index| 60 * slot_duration * index }

# i += 1
# event = events[i]

  # def replace_taken_times(first_array, second_array)
  #   first_array.map { |slot| second_array.include?(slot) ? '-' : slot }
  # end



# def availabilities_from(date, slot_duration = 30, week_duration = 6)
  #   date = DateTime.parse(date)
  #   date_range = date.beginning_of_day..(date.end_of_day + week_duration.days - 1.day)
  #   events = fetch(id, date_range)
  #   generate_results(events, date_range, slot_duration)
  # end

  # def fetch(id, date_range)
  #   days = date_range.map(&:wday)
  #   Availability.where(room_id: id, week_day: days) + Appointment.where('room_id = ? AND starts_at >= ? AND ends_at <= ?', id, date_range.begin, date_range.end)
  # end

  # def format_hash(date_range)
  #   date_range.each_with_object({}) { |day, hash| hash[day.strftime('%Y-%m-%d')] = [] }
  # end

  # def generate_week(date_range)
  #   date_range.each_with_object({}) { |day, hash| hash[day.wday] = day.strftime('%Y-%m-%d') }
  # end

  # def split_time_range(starts_at, ends_at, slot_duration = 30)
  #   time_range = []

  #   while starts_at < ends_at
  #     # time_range << [starts_at, starts_at + slot_duration.minutes]
  #     # time_range << starts_at.strftime('%H:%M')
  #     time_range << starts_at
  #     starts_at += (60 * slot_duration)
  #   end

  #   time_range
  # end

  # def transform_event(event, day)
  #   event.starts_at = DateTime.parse("#{day} #{event.starts_at.to_s(:time)}")
  #   event.ends_at = DateTime.parse("#{day} #{event.ends_at.to_s(:time)}")
  #   event
  # end

  # def replace_taken_times(first_array, second_array)
  #   first_array.map { |slot| second_array.include?(slot) ? '-' : slot }
  # end

  # def generate_results(events, date_range, slot_duration)
  #   results = format_hash(date_range)
  #   week = generate_week(date_range)

  #   events.each do |event|
  #     # i += 1
  #     # event = events[i]
  #     day = week[event.week_day]
  #     event = transform_event(event, day)
  #     slots = split_time_range(event.starts_at, event.ends_at, slot_duration)
  #     event.instance_of?(Availability) ? results[day] += slots : results[day] = replace_taken_times(results[day], slots)
  #   end

  #   results
  # end



# def clean_hash(hash)
#   hash.each_value do |array|
#     next unless array.join('').match?(/\d/)

#     array.each do |slot|
#       break if slot.match?(/\d/)

#       array.delete(slot)
#     end
#   end
# end



# time_range << starts_at.strftime("%H:%M")
#time_range << [starts_at.strftime('%FT%T%:z'), (starts_at + 60 * slot_duration).strftime('%FT%T%:z')]

#date_range.map { |day| day.strftime('%Y-%m-%d') }
# def availabilities_from(received_date, slot_duration)
#   date = today?(received_date) ? DateTime.now : DateTime.parse(received_date)

#   availabilities = fetch_and_transform_availabilities(id, date)
#   appointments = fetch_appointments(id, date)
#   substract_appointments_from_availabilities(availabilities, appointments, date, slot_duration)
# end

# private

# def today?(date)
#   date == Date.today.to_s
# end

# def modify_availability(availability, date)
#   loop do
#     availability.starts_at += 7 * 24 * 3600
#     availability.ends_at += 7 * 24 * 3600
#     break if availability.starts_at.to_date == date.to_date
#   end

#   availability
# end

# def fetch_and_transform_availabilities(room_id, date)
#   availabilities = Availability.where('room_id = ? AND week_day = ?', room_id, date.wday)
#   availabilities.map { |availability| modify_availability(availability, date) }
# end

# def fetch_appointments(room_id, date)
#   Appointment.where('room_id = ? AND starts_at >= ? AND ends_at <= ?', room_id, date.beginning_of_day, date.end_of_day)
# end

# def substract_appointments_from_availabilities(availabilities, appointments, date, slot_duration)
#   availabilities = availabilities.map { |availability| split_time_range(availability.starts_at, availability.ends_at, slot_duration) }.flatten
#   appointments = appointments.map { |appointment| split_time_range(appointment.starts_at, appointment.ends_at, slot_duration) }.flatten
#   results = (availabilities - appointments).uniq
#   # results.reject { |slot| slot <= date.strftime('%H:%M') }
# end

# base_time_range.each do |available_slot|
#   overlap = unavailable.map do |booked_slot|
#     (booked_slot[0]...(booked_slot[0] + booked_slot[1].hours)).overlaps?(available_slot...(available_slot + time_range[1].hours))
#   end

#   !overlap.include?(true) ? available_slots << slot : ''
# end

# def split_time_range(starts_at, ends_at, slot_duration = 30)
#   time_range = []

#   while starts_at < ends_at
#     time_range << (starts_at.strftime('%H:%M')...(starts_at + 60 * slot_duration).strftime('%H:%M'))
#     starts_at += (60 * slot_duration)
#   end

#   time_range
# end

# def make_range_for_appointments(appointments)
#   appointments.map do |appointment|
#     appointment.starts_at.strftime('%H:%M')...appointment.ends_at.strftime('%H:%M')
#   end
# end

# availabilities.map do |slot|
#   overlap = appointments.map { |booked_slot| (booked_slot).overlaps?(slot) }
#   overlap.include?(true) ? '-' : slot
# end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all.order(:id)
    @slot_duration = 30
    @week_duration = 5
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="w-full mx-auto rounded-lg bg-white shadow p-5 text-gray-800" style="max-width: 400px">
    <div class="w-full flex mb-4">
        <div class="overflow-hidden rounded-full w-12 h-12">
          <img src="https://images.unsplash.com/photo-1585128719562-74b7009c5776" alt="">
        </div>
        <div class="flex-grow pl-3 flex items-center">
          <%= form.label :name, class: "hidden" %>
          <%= form.text_field :name, class: "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"%>
          <%#= link_to room.name, room, class: "font-bold text-md hover:bg-white hover:text-gray-700" %>
        </div>
    </div>
    <div class="w-full mb-4 flex flex-row-reverse space-x-2 justify-start">
      <%= form.submit class: "ml-2 cursor-pointer inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
      <%= button_to 'Cancel', room, class: "cursor-pointer text-white inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
    </div>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<%= turbo_frame_tag dom_id(room) do %>
  <div class="w-full rounded-lg bg-white shadow p-5 text-gray-800 h-96 overflow-hidden overflow-y-scroll" data-controller="booking">
    <div class="w-full flex mb-4">
        <div class="overflow-hidden rounded-full w-12 h-12">
          <img src="https://images.unsplash.com/photo-1585128719562-74b7009c5776" alt="">
        </div>
        <div class="flex-grow pl-3 flex items-center">
          <%= link_to room.name, edit_room_path(room), class: "cursor-text font-bold text-md hover:bg-white hover:text-gray-700" %>
        </div>
        <div class="text-right flex items-center">
          <div class="relative inline-block text-left" data-controller="dropdown">
            <div data-action="click->dropdown#toggle click@window->dropdown#hide" role="button" data-dropdown-target="button" tabindex="0">
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-700 cursor-pointer" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
              </svg>
            </div>

            <div data-dropdown-target="menu" class="hidden origin-top-right absolute right-0 mt-2 rounded-md shadow-lg bg-white ring-1 ring-black ring-opacity-5 divide-y divide-gray-100 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
              <div class="py-1" role="none">
                <%= link_to 'Edit', edit_room_path(room), class: "text-gray-700 block px-4 py-2 text-sm hover:bg-gray-100 hover:text-gray-900" %>
                <%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-gray-700 block px-4 py-2 text-sm hover:bg-gray-100 hover:text-gray-900" %>
              </div>
            </div>
          </div>
        </div>
    </div>

    <div class="w-full mb-4 flex">
      <% availabilities = room.availabilities_from('2021-08-20', @slot_duration, @week_duration) %>
      <% if availabilities.any? %>
        <div class="w-12 flex justify-center items-start">
          Prev
        </div>
        <% availabilities.each do |day, array| %>
          <div class="day flex-grow mx-1 select-none">
            <div class="header items-center flex flex-col item-center mb-2">
              <div class="text-xs font-medium text-gray-600 leading-4"><%= Date::DAYNAMES[day.to_date.wday] %></div>
              <div class="flex items-center justify-center w-12 h-12 rounded-full text-2xl transition duration-150 ease-in-out focus:outline-none font-medium text-gray-700"><%= day.to_date.day %></div>
            </div>
            <% array.each do |slot| %>
              <% if slot != '-' %>
                <%= link_to slot.to_s(:time), appointments_path(appointment: { room_id: room.id, starts_at: slot, ends_at: slot + @slot_duration.minutes }), class: 'w-30 h-10 my-2 font-semibold cursor-pointer hover:bg-blue-600 hover:text-white rounded-md shadow-md bg-blue-200 text-blue-600 flex justify-center items-center', data: { turbo: false, method: :post, confirm: 'Are you sure ?' }  %>
              <% else %>
                <div class="w-30 h-10 my-2 font-semibold rounded-md bg-gray-200 text-gray-600 flex justify-center items-center"> - </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
        <div class="w-12 flex justify-center items-start">
          Next
        </div>
      <% else %>
      <p>No availabilities for this day</p>
      <% end %>
    </div>
  </div>
<% end %>

            <%#= link_to slot, { controller: 'appointments', action: 'create', user_id: current_user.id, room_id: room.id, method: 'post' }, class:   %>

app/views/rooms/edit.html.erb
<%= turbo_frame_tag dom_id(@room) do %>
  <%= render 'form', room: @room %>
<% end %>

app/views/rooms/index.html.erb
<h1 class="font-bold text-5xl py-4">Rooms</h1>
<%= link_to "se déconnecter", destroy_session_path(current_user), method: :delete %>
<%= Time.now.in_time_zone(current_user.time_zone) %>
<%= turbo_stream_from 'rooms' %>
<div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
  <%= render @rooms %>
</div>
<div>
  <%= link_to 'New Room', new_room_path %>
</div>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<%= turbo_frame_tag dom_id(@room) do %>
  <%= render @room %>
<% end %>