config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :appointments
  resources :availabilities
  resources :rooms
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "rooms#index"
end

app/models/availability.rb
class Availability < ApplicationRecord
  belongs_to :room
  # after_validation :convert_string_to_date_time

  # def convert_string_to_date_time
  #   date = week_day.zero? ? "1-11-2020" : "#{week_day}-03-2021"
  #   self.starts_at = DateTime.parse("#{date}  #{starts_at} ")
  #   self.ends_at = DateTime.parse("#{date}  #{ends_at} ")
  # end
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  before_action :set_availability, only: %i[ show edit update destroy ]

  # GET /availabilities or /availabilities.json
  def index
    @availabilities = Availability.all
  end

  # GET /availabilities/1 or /availabilities/1.json
  def show
  end

  # GET /availabilities/new
  def new
    @availability = Availability.new
  end

  # GET /availabilities/1/edit
  def edit
  end

  # POST /availabilities or /availabilities.json
  def create
    @availability = Availability.new(availability_params)

    respond_to do |format|
      if @availability.save
        format.html { redirect_to @availability, notice: "Availability was successfully created." }
        format.json { render :show, status: :created, location: @availability }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /availabilities/1 or /availabilities/1.json
  def update
    respond_to do |format|
      if @availability.update(availability_params)
        format.html { redirect_to @availability, notice: "Availability was successfully updated." }
        format.json { render :show, status: :ok, location: @availability }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /availabilities/1 or /availabilities/1.json
  def destroy
    @availability.destroy
    respond_to do |format|
      format.html { redirect_to availabilities_url, notice: "Availability was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_availability
      @availability = Availability.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def availability_params
      params.require(:availability).permit(:starts_at, :ends_at, :week_day, :room_id)
    end
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper
end

app/views/availabilities/_form.html.erb
<%= form_with(model: availability) do |form| %>
  <% if availability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(availability.errors.count, "error") %> prohibited this availability from being saved:</h2>

      <ul>
        <% availability.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :starts_at %>
    <%= form.datetime_select :starts_at %>
  </div>

  <div class="field">
    <%= form.label :ends_at %>
    <%= form.datetime_select :ends_at %>
  </div>

  <div class="field">
    <%= form.label :week_day %>
    <%= form.number_field :week_day %>
  </div>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.text_field :room_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/availabilities/edit.html.erb
<h1>Editing Availability</h1>

<%= render 'form', availability: @availability %>

<%= link_to 'Show', @availability %> |
<%= link_to 'Back', availabilities_path %>

app/views/availabilities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Availabilities</h1>

<table>
  <thead>
    <tr>
      <th>Starts at</th>
      <th>Ends at</th>
      <th>Week day</th>
      <th>Room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @availabilities.each do |availability| %>
      <tr>
        <td><%= availability.starts_at %></td>
        <td><%= availability.ends_at %></td>
        <td><%= availability.week_day %></td>
        <td><%= availability.room_id %></td>
        <td><%= link_to 'Show', availability %></td>
        <td><%= link_to 'Edit', edit_availability_path(availability) %></td>
        <td><%= link_to 'Destroy', availability, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Availability', new_availability_path %>

app/views/availabilities/new.html.erb
<h1>New Availability</h1>

<%= render 'form', availability: @availability %>

<%= link_to 'Back', availabilities_path %>

app/views/availabilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Starts at:</strong>
  <%= @availability.starts_at %>
</p>

<p>
  <strong>Ends at:</strong>
  <%= @availability.ends_at %>
</p>

<p>
  <strong>Week day:</strong>
  <%= @availability.week_day %>
</p>

<p>
  <strong>Room:</strong>
  <%= @availability.room_id %>
</p>

<%= link_to 'Edit', edit_availability_path(@availability) %> |
<%= link_to 'Back', availabilities_path %>